# Generated by Django 4.1.3 on 2022-11-22 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                ("identifiant", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("nom_du_festival", models.CharField(max_length=255)),
                ("discipline_dominante", models.CharField(max_length=255)),
                ("annee_de_creation", models.DateField()),
                ("site", models.URLField(blank=True, null=True)),
                ("periode", models.DurationField()),
                ("geolocalisation", models.DecimalField(decimal_places=6, max_digits=9)),
                ("region_principale", models.CharField(max_length=255)),
                ("department_principal", models.CharField(max_length=255)),
                ("commune_principale", models.CharField(max_length=255)),
                (
                    "code_postal_commune",
                    models.CharField(
                        max_length=5,
                        validators=[django.core.validators.RegexValidator("^[0-9]{5}$", "Invalid postal code")],
                    ),
                ),
            ],
            options={
                "db_table": "festival",
                "ordering": ["annee_de_creation"],
            },
        ),
    ]
