# Generated by Django 4.1.3 on 2022-11-22 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zhackathon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="code_postal_commune",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="commune_principale",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="festival",
            name="department_principal",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="festival",
            name="discipline_dominante",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="festival",
            name="identifiant",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="festival",
            name="nom_du_festival",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="festival",
            name="region_principale",
            field=models.CharField(max_length=100),
        ),
    ]
