# Generated by Django 4.1.3 on 2022-11-24 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zhackathon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="festival",
            field=models.ForeignKey(
                editable=False, on_delete=django.db.models.deletion.CASCADE, to="zhackathon.festival"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="liked_by",
            field=models.ManyToManyField(blank=True, related_name="comments_liked", to=settings.AUTH_USER_MODEL),
        ),
    ]
