# Generated by Django 4.1.3 on 2022-11-25 00:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zhackathon", "0002_alter_comment_author_alter_comment_festival_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="comment",
            name="festival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="zhackathon.festival"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="festival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="zhackathon.festival"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AlterField(
            model_name="ticketing",
            name="festival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ticketings", to="zhackathon.festival"
            ),
        ),
    ]
